# Generated by Django 4.2.11 on 2024-03-16 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppViewed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("country_code", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "continent_code",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "country_flag",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("uses_vpn", models.BooleanField(default=False)),
                ("model_object_id", models.PositiveBigIntegerField()),
            ],
            options={
                "verbose_name": "App Viewed",
                "verbose_name_plural": "Apps Viewed",
            },
        ),
        migrations.CreateModel(
            name="PageViews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("page_link", models.URLField()),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                (
                    "country_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=5, null=True
                    ),
                ),
                (
                    "continent_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=5, null=True
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "country_flag",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("uses_vpn", models.BooleanField(default=False)),
                ("last_visited_date", models.DateField(blank=True, null=True)),
                ("new_visit_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Page Viewed",
                "verbose_name_plural": "Pages Viewed",
            },
        ),
        migrations.CreateModel(
            name="ReviewRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("rating", models.IntegerField(default=1)),
                ("review_text", models.TextField(max_length=420)),
                ("model_object_id", models.PositiveBigIntegerField()),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "App Review",
                "verbose_name_plural": "Apps Review",
            },
        ),
    ]
