# Generated by Django 4.2.11 on 2024-03-16 13:08

import chowapi.users.managers
import chowapi.utils.files
import chowapi.utils.validators
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("management", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "unique_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name of User")),
                (
                    "phone",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[
                            chowapi.utils.validators.validate_phone_number_field
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                ("pin", models.CharField(max_length=6, verbose_name="pin")),
                ("country", models.CharField(blank=True, max_length=10, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=255, null=True)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                ("is_vendor", models.BooleanField(default=False)),
                ("is_customer", models.BooleanField(default=False)),
                ("is_rider", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", chowapi.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Activities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("identity", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[("LOGIN", "LOGIN"), ("SINGUP", "SINGUP")],
                        default="SINGUP",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserSessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("session_key", models.CharField(max_length=255, null=True)),
                ("ip_address", models.CharField(max_length=255, null=True)),
                (
                    "country_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=5, null=True
                    ),
                ),
                (
                    "continent_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=5, null=True
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "country_flag",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("uses_vpn", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("ended", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SaveDebitCards",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("card_number", models.CharField(max_length=24)),
                ("expiry_date", models.DateField()),
                ("active", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Card",
                "verbose_name_plural": "Saved Cards",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SavedAddresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("OFFICE", "OFFICE"),
                            ("RESIDENTIAL", "RESIDENTIAL"),
                            ("PARK", "PARK"),
                            ("HOTEL", "HOTEL"),
                            ("HOSPITAL", "HOSPITAL"),
                        ],
                        default="OFFICE",
                        max_length=50,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("longitude", models.CharField(max_length=50)),
                ("latitude", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Address",
                "verbose_name_plural": "Saved Addresses",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RiderParticulars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("id_number", models.CharField(blank=True, max_length=25)),
                (
                    "license",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=chowapi.utils.files.FileUploader.static_image_upload_path,
                        validators=[
                            chowapi.utils.validators.document_validate_file_extension
                        ],
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("MOTORCYCLE", "MOTORCYCLE"),
                            ("BICYCLE", "BICYCLE"),
                            ("WALKING", "WALKING"),
                        ],
                        default="BICYCLE",
                        max_length=20,
                    ),
                ),
                ("guarantor", models.CharField(blank=True, max_length=255)),
                ("guarantor_phone", models.CharField(blank=True, max_length=14)),
                ("guarantor_address", models.CharField(blank=True, max_length=500)),
                ("guarantor_longitude", models.CharField(blank=True, max_length=50)),
                ("guarantor_latitude", models.CharField(blank=True, max_length=50)),
                ("on_a_request", models.BooleanField(default=False)),
                ("validated", models.BooleanField(default=False)),
                (
                    "delivery_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_location",
                        to="management.deliverycitylocations",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_particular",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rider Particulars",
                "verbose_name_plural": "Rider Particulars",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=14, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("longitude", models.CharField(blank=True, max_length=50, null=True)),
                ("latitude", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "managed": True,
            },
        ),
    ]
