# Generated by Django 4.2.11 on 2024-03-16 13:08

import chowapi.utils.files
import chowapi.utils.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nutrition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Locations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=14)),
                ("longitude", models.CharField(max_length=50)),
                ("latitude", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=255)),
                ("website", models.URLField(max_length=500)),
            ],
            options={
                "verbose_name": "Vendor Location",
                "verbose_name_plural": "Vendor Locations",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MenuItemOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("delivery_lat", models.CharField(blank=True, max_length=50)),
                ("delivery_lon", models.CharField(blank=True, max_length=50)),
                ("delivery_address", models.CharField(blank=True, max_length=500)),
                (
                    "order_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=225, unique=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                ("paid", models.BooleanField(default=False)),
                ("failed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_order",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MenuItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("unique_id", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(max_length=420)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Currency is in USD. Set the value in USD and we would do the conversion to other currencies",
                        max_digits=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Menu Item",
                "verbose_name_plural": "Food Menu Items",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="VendorCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Vendor Category",
                "verbose_name_plural": "Vendor Categroies",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="VendorShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("slug", models.SlugField(blank=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "logo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=chowapi.utils.files.FileUploader.vendor_logo_image_upload_path,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="vendor_categories", to="vendors.vendorcategory"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="representatives", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Store",
                "verbose_name_plural": "Vendor Stores",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="VendorsEarnings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
                ),
                (
                    "payout",
                    models.IntegerField(
                        choices=[("MONTHLY", 1), ("QUARTERLY", 4), ("YEARLY", 12)],
                        default=1,
                    ),
                ),
                ("payout_date", models.DateField(blank=True, null=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earning",
                        to="vendors.vendorshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Earning",
                "verbose_name_plural": "Vendor Earnings",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="OpenHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("day", models.CharField(max_length=255)),
                ("open", models.TimeField()),
                ("close", models.TimeField()),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_hours",
                        to="vendors.vendorshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor Service Hour",
                "verbose_name_plural": "Vendor Service Hours",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MenuNutritionalValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("calories", models.FloatField(default=0)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition",
                        to="vendors.menuitems",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition",
                        to="nutrition.nutrition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutritional Value",
                "verbose_name_plural": "Nutritional Values",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="menuitems",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="vendors.vendorshop",
            ),
        ),
        migrations.CreateModel(
            name="MenuItemOrderPickupLocations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_location",
                        to="vendors.locations",
                    ),
                ),
                (
                    "meals",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_item",
                        to="vendors.menuitems",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="vendors.menuitemorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Location",
                "verbose_name_plural": "Order Locations",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="MenuItemImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("caption", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=chowapi.utils.files.FileUploader.food_image_upload_path,
                        validators=[
                            chowapi.utils.validators.image_validate_file_extension
                        ],
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_images",
                        to="vendors.menuitems",
                    ),
                ),
            ],
            options={
                "verbose_name": "Food Image",
                "verbose_name_plural": "Food Images",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="locations",
            name="vendor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="vendors.vendorshop",
            ),
        ),
        migrations.CreateModel(
            name="DeliveryDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("eta", models.DateTimeField(blank=True, null=True)),
                ("distance_to_arrival", models.FloatField(default=1.0)),
                ("delivered", models.BooleanField(default=False)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_detail",
                        to="vendors.menuitemorder",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_delivery_detail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery Detail",
                "verbose_name_plural": "Deliveries Detail",
                "managed": True,
            },
        ),
    ]
