# Generated by Django 4.2.11 on 2024-03-18 13:20

import chowapi.utils.files
import chowapi.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0002_remove_locations_email_remove_locations_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorshop",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="menuitemimages",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=chowapi.utils.files.FileUploader.food_image_upload_path,
                validators=[chowapi.utils.validators.image_validate_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="vendorshop",
            name="logo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=chowapi.utils.files.FileUploader.vendor_logo_image_upload_path,
            ),
        ),
    ]
