# Generated by Django 4.2.11 on 2024-03-18 14:22

import chowapi.utils.files
import chowapi.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vendors",
            "0005_remove_vendorshop_country_remove_vendorshop_currency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitemimages",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=chowapi.utils.files.FileUploader.food_image_upload_path,
                validators=[chowapi.utils.validators.image_validate_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="vendorshop",
            name="logo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=chowapi.utils.files.FileUploader.vendor_logo_image_upload_path,
            ),
        ),
    ]
