# Generated by Django 4.2.11 on 2024-03-18 13:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_vendorshop_is_active_alter_menuitemimages_file_and_more"),
        ("otp", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorOTPs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("otp", models.CharField(db_index=True, max_length=7)),
                ("expired", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp",
                        to="vendors.vendorshop",
                    ),
                ),
            ],
        ),
    ]
